### ISSUE TITLE
Native video play in presentation

### ISSUE THREAD

**Issue by lp35** [ONLYOFFICE/plugin-youtube#15] opened 2020-12-07 13:03 UTC
Hi!

Thank you very much for this wonderful plugin.

As far as I tested, it is not possible to add a playable video directly in the presentation viewer ([MSOffice features this in PowerPoint](https://support.microsoft.com/en-us/office/video-add-format-and-record-video-bb7fc99c-71ef-48e3-ac1a-3ebafcd9f3ed)).

The only way I have found  is to create an URL that open the video in another tab.

Is it possible to add embedded video playing directly in presentation?

Thank you for your time,

Current Version: OnlyOffice 6.0.1.32

**Comment by shu0406** [comment] 2021-12-01 14:18
Same problem here. It's said that you have to double tab on the video using the plugin. But in presentation the presentation jumps to the next slide, so there is no chance to open that video directly in the presentation.

**Comment by ShockwaveNN** [comment] 2021-12-01 14:37
> But in presentation the presentation jumps to the next slide, so there is no chance to open that video directly in the presentation.

Hi, I've just checked it on v6.4.2 and youtube is playing OK in presentation editor. See this video:


https://user-images.githubusercontent.com/668524/144253372-0751dae6-9a0c-4548-92c0-6860afc21425.mp4


So this may be some bug so we need some more details about your environment and product version

**Comment by ShockwaveNN** [comment] 2021-12-01 14:51
And about OP (sorry, we missed that)

We already have an issue about playing video in presentation https://github.com/ONLYOFFICE/DocumentServer/issues/1534

And there is no any significant news, because implementing video player is very complicated task

**Comment by shu0406** [comment] 2021-12-01 16:35
Hi, thanks for the quick response but the problem is not the plugin itself but if you start a presentation you can not click the video anymore since the click means "next slide". Maybe you need a keyboard shortcut there like ctrl + v = starts video

**Comment by ShockwaveNN** [comment] 2021-12-02 07:36
Ah, got it, you mean slideshow view, when application show presentation on full screen - I think it's part of same issue [1534](https://github.com/ONLYOFFICE/DocumentServer/issues/1534)

Until we are able to play video directly in canvas without calling another iframe - I think cannot make videos play in slideshow view 

So I think I'll close this issue in favor of #1534

**Closed** 2021-12-02 07:42 UTC
